"""SQL validation layer.

Every query generated by the LLM passes through here BEFORE execution:
 1. exactly one statement
 2. statement type is SELECT
 3. only events / quality_flags / raw_patients tables
 4. no comments / injection constructs / forbidden keywords
 5. LIMIT present and <= 100 (appended if missing)
 6. every identifier is a known column, function, or safe literal
On rejection the caller may retry once, feeding the reason back to the model.
"""
from __future__ import annotations

import sqlparse
from sqlparse import tokens as T

ALLOWED_TABLES = {"events", "quality_flags", "raw_patients"}
ALLOWED_TABLES_UPPER = {t.upper() for t in ALLOWED_TABLES}

ALLOWED_COLUMNS = {
    "event_id", "patient_id", "encounter_id", "event_type", "event_subtype",
    "value", "value_numeric", "unit", "event_timestamp", "source_table", "source_row_id",
    "flag_id", "flag_type", "rule_id", "description", "reversible",
    "subject_id", "gender", "anchor_age",
}
ALLOWED_COLUMNS_UPPER = {c.upper() for c in ALLOWED_COLUMNS}

ALLOWED_FUNCTIONS = {
    "COUNT", "MIN", "MAX", "AVG", "SUM", "ROUND", "CAST", "LOWER", "UPPER",
    "ABS", "DATE", "DATETIME", "STRFTIME", "TYPEOF", "LENGTH", "GROUP_CONCAT", "COALESCE",
}

SAFE_LITERALS = {"NULL", "REAL", "INTEGER", "TEXT", "NUMERIC", "TRUE", "FALSE"}

FORBIDDEN_KEYWORDS = {
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "PRAGMA", "ATTACH",
    "CREATE", "TRUNCATE", "REPLACE", "VACUUM", "REINDEX", "BEGIN", "COMMIT",
    "ROLLBACK", "EXPLAIN", "EXEC", "CALL", "MERGE", "UNION", "INTERSECT",
    "EXCEPT", "INTO", "GLOB", "REGEXP", "MATCH",
}

# SQL keywords that are structural (neither tables nor columns).
STRUCTURAL_KEYWORDS = {
    "FROM", "JOIN", "WHERE", "AND", "OR", "NOT", "GROUP", "BY", "ORDER", "HAVING",
    "ON", "LIMIT", "AS", "IN", "BETWEEN", "LIKE", "IS", "DISTINCT", "CASE",
    "WHEN", "THEN", "ELSE", "END", "ASC", "DESC", "EXISTS", "NULL", "SELECT",
}

NAME_TYPES = (T.Name, T.Name.Plain, T.Name.Quoted, T.Name.Quoted.Double, T.Name.Quoted.Single)
NUMBER_TYPES = (T.Literal.Number.Integer, T.Literal.Number.Float)
STRING_TYPES = (T.Literal.String.Single, T.Literal.String.Symbol)
COMMENT_TYPES = (T.Comment, T.Comment.Single, T.Comment.Multiline)
WHITESPACE_TYPES = (T.Text.Whitespace, T.Text.Whitespace.Newline)


def _flatten(statement):
    for tok in statement.tokens:
        if tok.is_group:
            yield from _flatten(tok)
        else:
            yield tok


def _is_name(tok) -> bool:
    return tok.ttype in NAME_TYPES


def validate(sql: str) -> tuple[bool, str | None, str | None]:
    """Returns (ok, cleaned_sql, reason). cleaned_sql is None when rejected."""
    if not sql or not sql.strip():
        return False, None, "empty query"

    parsed = sqlparse.parse(sql)
    if not parsed:
        return False, None, "unparseable SQL"
    if len(parsed) > 1:
        return False, None, "multiple statements"

    stmt = parsed[0]
    if stmt.get_type().upper() != "SELECT":
        return False, None, f"statement type is {stmt.get_type()}, not SELECT"

    tokens = list(_flatten(stmt))

    def peek_name(i: int):
        """Name token at or after index i, skipping whitespace."""
        j = i
        while j < len(tokens) and tokens[j].ttype in WHITESPACE_TYPES:
            j += 1
        if j < len(tokens) and _is_name(tokens[j]):
            return tokens[j]
        return None

    tables: set[str] = set()
    aliases: set[str] = set()
    seen_patient_where = False
    seen_subject_where = False
    in_where = False
    seen_limit = False
    limit_value = None
    expect_table = False
    prev_was_as = False
    after_dot = False

    for i, tok in enumerate(tokens):
        ttype = tok.ttype
        upper = tok.value.upper().strip()

        if ttype in COMMENT_TYPES:
            return False, None, "comments are not allowed"
        if ttype in WHITESPACE_TYPES:
            continue

        # ---- keywords ----
        if ttype == T.Keyword or ttype == T.Keyword.DML or ttype == T.Keyword.DDL:
            if upper == "SELECT":
                continue
            if ttype == T.Keyword.DML or ttype == T.Keyword.DDL:
                return False, None, f"forbidden keyword {upper}"
            if upper in FORBIDDEN_KEYWORDS:
                return False, None, f"forbidden keyword {upper}"
            # Track whether we are inside a WHERE clause: only patient_id /
            # subject_id referenced *there* counts as a patient filter.
            # A bare `patient_id` in GROUP BY / SELECT / ON would pass an
            # existence check but filter nothing (SQA BUG #1).
            if upper == "WHERE":
                in_where = True
            elif upper in ("GROUP", "ORDER", "HAVING", "LIMIT", "JOIN", "ON", "BY"):
                in_where = False
            if upper in ("FROM", "JOIN"):
                expect_table = True
            elif upper == "LIMIT":
                seen_limit = True
            elif upper == "AS":
                prev_was_as = True
            elif upper.split()[0] in STRUCTURAL_KEYWORDS:
                expect_table = False  # FROM/JOIN clause is over once WHERE/ON/... appears
                pass
            else:
                # sqlparse classifies some table/column names as plain keywords.
                if expect_table:
                    if upper in ALLOWED_TABLES_UPPER:
                        tables.add(upper)
                    else:
                        expect_table = False  # table alias
                else:
                    if upper.upper() == "PATIENT_ID":
                        if in_where:
                            seen_patient_where = True
                    if upper.upper() == "SUBJECT_ID":
                        if in_where:
                            seen_subject_where = True
                    if upper.lower() not in ALLOWED_COLUMNS:
                        return False, None, f"unknown identifier {tok.value}"
            after_dot = False
            continue

        # ---- punctuation ----
        if ttype == T.Punctuation:
            if tok.value == ".":
                after_dot = True
            else:
                after_dot = False
            prev_was_as = False
            continue

        # ---- literals / numbers / strings / operators / wildcards ----
        if ttype in NUMBER_TYPES:
            if seen_limit and limit_value is None:
                limit_value = int(float(tok.value))
            after_dot = False
            continue
        if ttype in STRING_TYPES:
            after_dot = False
            continue
        if ttype == T.Name.Placeholder:
            return False, None, "parameter placeholders are not allowed"
        if ttype == T.Wildcard or tok.value == "*":
            after_dot = False
            continue
        if ttype in (T.Operator, T.Operator.Comparison, T.Operator.Logical, T.Operator.Assignment, T.Operator.Wildcard):
            after_dot = False
            continue

        # ---- names / identifiers ----
        if _is_name(tok):
            name = tok.value.strip().strip('"`[]')
            if expect_table:
                if name.upper() in ALLOWED_TABLES_UPPER:
                    tables.add(name.upper())
                    expect_table = True
                else:
                    expect_table = False  # alias
                prev_was_as = False
                after_dot = False
                continue
            if after_dot:
                # alias-qualified column, e.g. e.event_id
                if name.upper() == "PATIENT_ID":
                    if in_where:
                        seen_patient_where = True
                if name.upper() == "SUBJECT_ID":
                    if in_where:
                        seen_subject_where = True
                if name.upper() not in ALLOWED_COLUMNS_UPPER:
                    return False, None, f"unknown identifier {name}"
                after_dot = False
                prev_was_as = False
                continue
            if prev_was_as:
                aliases.add(name.upper())
                prev_was_as = False
                continue
            if name.upper() in SAFE_LITERALS or name.upper() in ALLOWED_FUNCTIONS:
                continue
            # alias-qualified column reference, e.g. "e . event_id": the name is
            # followed by a '.'; the column name after the dot is validated above.
            j = i + 1
            while j < len(tokens) and tokens[j].ttype in WHITESPACE_TYPES:
                j += 1
            if j < len(tokens) and tokens[j].ttype == T.Punctuation and tokens[j].value == ".":
                prev_was_as = False
                after_dot = False
                continue
            if name.upper() in aliases:
                prev_was_as = False
                after_dot = False
                continue
            if name.upper() == "PATIENT_ID":
                if in_where:
                    seen_patient_where = True
            if name.upper() == "SUBJECT_ID":
                if in_where:
                    seen_subject_where = True
            if name.upper() not in ALLOWED_COLUMNS_UPPER:
                return False, None, f"unknown identifier {name}"
            prev_was_as = False
            after_dot = False
            continue

        after_dot = False

    if tables - ALLOWED_TABLES_UPPER:
        return False, None, f"disallowed table(s): {tables - ALLOWED_TABLES_UPPER}"
    if not tables:
        return False, None, "no table referenced"
    if not seen_patient_where and not (seen_subject_where and "RAW_PATIENTS" in tables):
        return False, None, "query does not filter by patient_id in a WHERE clause (required for patient isolation)"
    if seen_limit and limit_value is not None and limit_value > 100:
        return False, None, f"LIMIT {limit_value} exceeds 100"

    cleaned = sql.strip()
    if not seen_limit:
        cleaned = cleaned.rstrip().rstrip(";") + " LIMIT 100"
    return True, cleaned, None
